# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'waitUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(611, 501)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 7);\n"
"color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.elem_name_LN = QtWidgets.QFrame(self.centralwidget)
        self.elem_name_LN.setGeometry(QtCore.QRect(10, 200, 580, 1))
        self.elem_name_LN.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.elem_name_LN.setLineWidth(1)
        self.elem_name_LN.setFrameShape(QtWidgets.QFrame.HLine)
        self.elem_name_LN.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.elem_name_LN.setObjectName("elem_name_LN")
        self.top_LN = QtWidgets.QFrame(self.centralwidget)
        self.top_LN.setGeometry(QtCore.QRect(0, 0, 600, 1))
        self.top_LN.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.top_LN.setLineWidth(1)
        self.top_LN.setFrameShape(QtWidgets.QFrame.HLine)
        self.top_LN.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.top_LN.setObjectName("top_LN")
        self.bottom_LN = QtWidgets.QFrame(self.centralwidget)
        self.bottom_LN.setGeometry(QtCore.QRect(0, 500, 600, 1))
        self.bottom_LN.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.bottom_LN.setLineWidth(1)
        self.bottom_LN.setFrameShape(QtWidgets.QFrame.HLine)
        self.bottom_LN.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.bottom_LN.setObjectName("bottom_LN")
        self.elem_name_LN_2 = QtWidgets.QFrame(self.centralwidget)
        self.elem_name_LN_2.setGeometry(QtCore.QRect(10, 300, 580, 1))
        self.elem_name_LN_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.elem_name_LN_2.setLineWidth(1)
        self.elem_name_LN_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.elem_name_LN_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.elem_name_LN_2.setObjectName("elem_name_LN_2")
        self.wait_LBL = QtWidgets.QLabel(self.centralwidget)
        self.wait_LBL.setGeometry(QtCore.QRect(10, 210, 581, 81))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setItalic(True)
        self.wait_LBL.setFont(font)
        self.wait_LBL.setAlignment(QtCore.Qt.AlignCenter)
        self.wait_LBL.setObjectName("wait_LBL")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.wait_LBL.setText(_translate("MainWindow", "Caricamento profilo in corso..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
