AC-PV:
  Hourly_Degradation:
    rate: 0.2
      
  Partial_Shading:
    scale:
      lambda_a: 1095
      lambda_duration: 3
      is_fixed: False
      value: 0.7
      
  Dust:
    (-x+1) decrease:
      lambda_a: 1
      lambda_duration: 1.5
      is_fixed: False
      alpha: 0.5

  Hot_Spot:
    scale:
      lambda_a: 1
      lambda_duration: 4
      is_fixed: False
      value: 0.5
        
DC-PV:
  Hourly_Degradation:
    rate: 0.2
  
  Partial_Shading:
    scale: 
      lambda_a: 1095
      lambda_duration: 3
      is_fixed: False
      value: 0.7    
  Dust:
    (-x+1) decrease: 
      lambda_a: 1
      lambda_duration: 1.5
      is_fixed: False
      alpha: 0.5
    (-x+1) antonio:
      lambda_a: 1
      lambda_duration: 1.5
      is_fixed: False
      alpha: 0.5
  Hot_Spot: 
    scale: 
      lambda_a: 1
      lambda_duration: 4
      is_fixed: False
      value: 0.5
      
AC-Wind:
  Hourly_Degradation:
    rate: 0.016

  Icing:
    scale:
      lambda_a: 5
      lambda_duration: 10
      is_fixed: False
      value: 0.3

DC-Wind:
  Hourly_Degradation:
    rate: 0.016

  Icing:
    scale:
      lambda_a: 5
      lambda_duration: 10
      is_fixed: False
      value: 0.3

AC-BESS:
  Hourly_Degradation:
    rate: 0.0137

DC-BESS:
  Hourly_Degradation:
    rate: 0.0137

FC:
  Hourly_Degradation:
    rate: 0.01

  Crepa_Membrana:
    (1-exp) decrease:
      lambda_a: 0.2
      lambda_duration: -1
      is_fixed: False
      alpha: 13.8

  Foratura Membrana:
    (1-exp) decrease:
      lambda_a: 0.2
      lambda_duration: -1
      is_fixed: False
      alpha: 3.45

  CrossOver H2:
    (1-exp) decrease:
      lambda_a: 0.2
      lambda_duration: 20
      is_fixed: False
      alpha: 73

  Sintering:
    (-x+1) decrease:
      lambda_a: 0.2
      lambda_duration: 20
      is_fixed: False
      alpha: 3

  Contaminazione catalizzatore:
    (-x+1) decrease:
      lambda_a: 0.2
      lambda_duration: 20
      is_fixed: False
      alpha: 3

  Contaminazione supporto:
    (-x+1) decrease:
      lambda_a: 0.2
      lambda_duration: 20
      is_fixed: False
      alpha: 3

  Allagamento catodo:
    (-x+1) decrease:
      lambda_a: 0.2
      lambda_duration: 20
      is_fixed: False
      alpha: 146
